SYSTEM_UID = 1
ROOT_UID = 2
OWNER_UID = 3
SAMPLE_DATA_UID = 97
UNIT_TESTER_UID = 98
NOBODY_UID = 99
NOBODY_PRINCIPAL = 'nobody'
NOBODY_EMAIL = 'nobody@localhost'
NOBODY_DISPLAY_NAME = 'Nobody'

SYSTEM_RID = 1
WHEEL_RID = 2
USERS_RID = 10
UNIT_TESTERS_RID = 98
EVERYONE_RID = 99

NODE_NAME_SYS_AUTH_MGR = 'auth_mgr'
NODE_NAME_SYS_AUTH_USER_MGR = 'user_mgr'
NODE_NAME_SYS_AUTH_GROUP_MGR = 'group_mgr'
NODE_NAME_SYS_AUTH_GROUP_MEMBER_MGR = 'group_member_mgr'
NODE_NAME_SYS_AUTH_PERMISSION_MGR = 'permission_mgr'

GROUP_KIND_SYSTEM = 'system'
GROUP_KIND_TENANT = 'tenant'

PERM_ALL = '*'
